language: cpp

# http://docs.travis-ci.com/user/multi-os/
os:
 - linux
 - osx

compiler:
 - gcc
 - clang

env:
  matrix:
   - BUILDTYPE=Release
   - BUILDTYPE=Debug

cache:
- apt
- directories:
  - mapnik-packaging

before_install:
- source ./scripts/install_build_deps_${TRAVIS_OS_NAME}.sh
- source ./setup-libraries.sh

install:
- rm -rf mapnik-packaging/out/packages

before_script:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ ${CXX} == "g++" ]]; then export CXX="g++-4.8" ; fi

script:
- make llmr BUILDTYPE=${BUILDTYPE}
- make clean
- make ${TRAVIS_OS_NAME} BUILDTYPE=${BUILDTYPE}
- make clean
- make run-tests BUILDTYPE=${BUILDTYPE}
# TODO - port this test to linux
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make run-headless-test BUILDTYPE=${BUILDTYPE} ; fi

notifications:
- hipchat: WB52YkcbCGMbNcStsGeaoRO7cyBSK4wX2ZHo2Y4b@GL

git:
  submodules: false
